<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Driver\Module'                        => __DIR__ . '/Module.php',
    'Driver\Controller\DriverController' => __DIR__ . '/src/Driver/Controller/DriverController.php',
    'DriverTest\Framework\TestCase'        => __DIR__ . '/tests/Driver/Framework/TestCase.php',
    'DriverTest\SampleTest'                => __DIR__ . '/tests/Driver/SampleTest.php',
);
