<!-- Begin Sign Up -->
						<div role="tabpanel" class="tab-pane" id="signup"
							aria-labelledby="signup-tab">
							<h3>Create An Account</h3>
							<form>
								<div class="group material-input">
									<input type="text" required> <span class="highlight"></span> <span
										class="bar"></span> <label>Email</label>
								</div>
								<div class="group material-input">
									<input type="password" required> <span class="highlight"></span>
									<span class="bar"></span> <label>Password</label>
								</div>
								<div class="group material-input">
									<input type="password" required> <span class="highlight"></span>
									<span class="bar"></span> <label>Confirm Password</label>
								</div>
							</form>
							<div class="row">
								<div class="col text-left">
									<div class="styled-checkbox">
										<input type="checkbox" name="checkbox" id="agree"> <label
											for="agree">I Accept <a href="#">Terms and Conditions</a></label>
									</div>
								</div>
							</div>
							<div class="sign-btn text-center">
								<a href="db-default.html" class="btn btn-lg btn-gradient-01">
									Sign Up </a>
							</div>
						</div>
						<!-- End Sign Up -->