<!-- Begin Sign Up -->
<div role="tabpanel" class="tab-pane" id="signup" aria-labelledby="signup-tab">
	<h3>Create An Account</h3>
	<form>

		<div class="group material-input">
			<input type="text" v-model='fullname' ref="fullname"  required> <span class="highlight"></span> <span class="bar"></span> <label>Full Name</label>
		</div>

		<div class="group material-input">
			<input type="text" v-model="phoneNumber" @input="acceptNumber" ref="phoneNumber"  required> <span class="highlight"></span> <span class="bar"></span> <label>Phone Number</label>
		</div>

		<div class="group material-input">
			<input type="text" v-model="email" ref="email"  required> <span class="highlight"></span> <span class="bar"></span> <label>Email</label>
		</div>


		<div class="group material-input">
			<input type="password" v-model="password" required> <span class="highlight"></span>
			<span class="bar"></span> <label>Password</label>
		</div>
		<div class="group material-input">
			<input type="password" v-model="confirm_parrword" ref="confirm_parrword" required> <span class="highlight"></span>
			<span class="bar"></span> <label>Confirm Password</label>
		</div>
	</form>
	<div class="row">
		<div class="col text-left">
			<div class="styled-checkbox">
				<input type="checkbox" name="checkbox" v-model="isterms" id="agree"> <label for="agree">I Accept <a href="#">Terms and Conditions</a></label>
			</div>
		</div>
	</div>
	<div class="sign-btn text-center">
		<button type="button" :disabled="submitStatus" @click="register()" class="btn btn-lg btn-gradient-01">
			Sign Up </button>
	</div>
</div>
<!-- End Sign Up -->


<script>
	Vue.use(VueToast, {
		// One of options
		position: 'top'
	});

	let = new Vue({
		el: "#signup",
		data() {
			return {
				phoneNumber: "",
				email: "",
				reg: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,24}))$/,
				fullname: "",
				confirm_parrword: "",
				isterms:false;
				password: ""

			}
		},

		computed: {
			submitStatus() {
				if (this.phoneNumber == "" || this.email == "" || this.fullname == "" || this.password == '' || this.confirm_parrword == '' || !this.isEmailValid) {
					return true;
				} else {
					return false;
				}


			},

			isEmailValid() {
				return this.reg.test(this.email);
			}
		},

		methods: {
			register() {
				console.log(this.reg.test(this.email));
			},

			acceptNumber() {
				var x = this.phoneNumber.replace(/\D/g, '').match(/(\d{0,4})(\d{0,3})(\d{0,4})/);
				this.phoneNumber = !x[2] ? x[1] : '' + x[1] + '-' + x[2] + (x[3] ? '-' + x[3] : '');
			}
		},
	});
</script>