<?php
echo $this->headtitle("Booking");

?>
<div id="viewbooking">
<section class="page--header">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6">
				<!-- Page Title Start -->
				<h2 class="page--title h5">Booking View</h2>
				<!-- Page Title End -->


			</div>

			<!-- 			<div class="col-lg-6"> -->
			<!-- Summary Widget Start -->
			<!-- 				<div class="summary--widget"> -->
			<!-- 					<div class="summary--item"> -->
			<!-- 						<p class="summary--chart" data-trigger="sparkline" data-type="bar" -->
			<!-- 							data-width="5" data-height="38" data-color="#009378">2,9,7,9,11,9,7,5,7,7,9,11</p> -->

			<!-- 						<p class="summary--title">This Month</p> -->
			<!-- 						<p class="summary--stats text-green">2,371,527</p> -->
			<!-- 					</div> -->

			<!-- 					<div class="summary--item"> -->
			<!-- 						<p class="summary--chart" data-trigger="sparkline" data-type="bar" -->
			<!-- 							data-width="5" data-height="38" data-color="#e16123">2,3,7,7,9,11,9,7,9,11,9,7</p> -->

			<!-- 						<p class="summary--title">Last Month</p> -->
			<!-- 						<p class="summary--stats text-orange">2,527,371</p> -->
			<!-- 					</div> -->
			<!-- 				</div> -->
			<!-- Summary Widget End -->
			<!-- 			</div> -->
		</div>
	</div>
</section>


<section class="main--content">
	<div class="panel">
		<!-- Records Header Start -->
		<div class="records--header">
			<div class="title fa-shopping-bag">
				<h3 class="h3">
					Booking Details <a href="#" class="btn btn-sm btn-outline-info">Process
						Booking</a>
				</h3>
			</div>
		</div>
		<!-- Records Header End -->
	</div>

	<div class="panel">

		<!-- View Order Start -->
		<div class="records--body">
			<div class="title">
				<h6 class="h6">
					BOOKING REF # <?php  echo strtoupper($data->getBookingUid())?><span
						class="text-lightergray"> - <?php  echo $this->dateformat($data->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_us")?>
						</span>
						<button class="btn btn-danger"><?php  echo $data->getStatus()->getStatus() ?></button>
				</h6>
			</div>

			<!-- Tabs Nav Start -->
			<ul class="nav nav-tabs">
				<li class="nav-item"><a href="#tab01" data-toggle="tab"
					class="nav-link active">Overview</a></li>
				<li class="nav-item"><a href="#tab02" data-toggle="tab"
					class="nav-link">BOOKING STATUS</a></li>
			</ul>
			<!-- Tabs Nav End -->

			<!-- Tab Content Start -->
			<div class="tab-content">
				<!-- Tab Pane Start -->
				<div class="tab-pane fade show active" id="tab01">
					<div class="row">
						<div class="col-md-6">
							<h4 class="subtitle">Order Information</h4>

							<table class="table table-simple">
								<tbody>
									<tr>
										<td>BOOKING REF:</td>
										<th><a href="#" class="btn-link"><?php  echo strtoupper($data->getBookingUid())?></a> </th>
									</tr>
									<tr>
										<td>Order Number:</td>
										<th>1231234123</th>
									</tr>
									<tr>
										<td>Booking Start On</td>
										<th><?php  echo $this->dateformat($data->getStartTime(), IntlDateFormatter::LONG, IntlDateFormatter::SHORT, "en_us")?></th>
									</tr>
									<tr>
										<td>Booking End On:</td>
										<th><?php  echo $this->dateformat($data->getEndTime(), IntlDateFormatter::LONG, IntlDateFormatter::SHORT, "en_us")?></th>
									</tr>
									<tr>
										<td>Booking TYpe </td>
										<th><span class="label label-success"><?php  echo $data->getBookingType()->getBookingType()?></span></th>
									</tr>
									<tr>
										<td>Service Type</td>
										<th><span class="label label-warning"><?php  echo $data->getBookingClass()->getBookingClass()?></span></th>
									</tr>
									<tr>
										<td>Amount Payed:</td>
										<th><?php  echo $this->myCurrency($data->getTransaction()->getAmount())?></th>
									</tr>
									<tr>
										<td>Payment Method:</td>
										<th>Credit Card</th>
									</tr>
								</tbody>
							</table>
						</div>

						<div class="col-md-6">
							<h4 class="subtitle">Users Information</h4>

							<table class="table table-simple">
								<tbody>

									<tr>
										<td>Users ID:</td>
										<th><?php  echo strtoupper($data->getUser()->getUserUid())?></th>
									</tr>
									<tr>
										<td>Users Name:</td>
										<th><?php  echo $data->getUser()->getFullName()?></th>
									</tr>
									<tr>
										<td>User Email</td>
										<th><?php  echo $data->getUser()->getEmail()?></th>
									</tr>
									<tr>
										<td>Users Phone</td>
										<th><?php  echo $data->getUser()->getPhoneNumber()?></th>
									</tr>
									<tr>
										<td>Registered On</td>
										<th><?php  echo $this->dateformat($data->getUser()->getRegistrationDate(), IntlDateFormatter::FULL, IntlDateFormatter::NONE)?></th>
									</tr>

									<tr>
										<td>Users Staus:</td>
										<th>0123 1234 123</th>
									</tr>
									<tr>
										<td>Users Last Login </td>
										<th><?php  echo $this->dateformat($data->getUser()->getLastlogin()->getLastlogin(), IntlDateFormatter::FULL, IntlDateFormatter::NONE)?></th>
									</tr>
									
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<!-- Tab Pane End -->

				<!-- Tab Pane Start -->
				<div class="tab-pane fade" id="tab02">
					<div class="row">
						<div class="col-md-6">
							<h4 class="subtitle">Order Information</h4>

							<table class="table table-simple">
								<tbody>
									<tr>
										<td>Customer Name:</td>
										<th><a href="#" class="btn-link">Justin Adams</a></th>
									</tr>
									<tr>
										<td>Order Number:</td>
										<th>1231234123</th>
									</tr>
									<tr>
										<td>Date:</td>
										<th>June 15, 2017 02:30</th>
									</tr>
									<tr>
										<td>Total Amount:</td>
										<th>$2587.00</th>
									</tr>
									<tr>
										<td>VAT (10%):</td>
										<th>$25</th>
									</tr>
									<tr>
										<td>Item Numbers:</td>
										<th>08</th>
									</tr>
									<tr>
										<td>Client History:</td>
										<th>4 Past Orders</th>
									</tr>
									<tr>
										<td>Payment Method:</td>
										<th>Credit Card</th>
									</tr>
								</tbody>
							</table>
						</div>

						<div class="col-md-6">
							<h4 class="subtitle">Other Information</h4>

							<table class="table table-simple">
								<tbody>
									<tr>
										<td>Ship To:</td>
										<th>Bertt Harris</th>
									</tr>
									<tr>
										<td>Destination:</td>
										<th>#24 Park Avenue Str., New York</th>
									</tr>
									<tr>
										<td>Delivery Date:</td>
										<th>June 16, 2017</th>
									</tr>
									<tr>
										<td>Shipping Method:</td>
										<th>Plane</th>
									</tr>
									<tr>
										<td>Shipment Status:</td>
										<th>Pending</th>
									</tr>
									<tr>
										<td>Phone Number:</td>
										<th>0123 1234 123</th>
									</tr>
									<tr>
										<td>Email:</td>
										<th>john@example.com</th>
									</tr>
									<tr>
										<td>Notes:</td>
										<th>Lorem ipsum dolor sit amet.</th>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<!-- Tab Pane End -->
			</div>
			<!-- Tab Content End -->
		</div>
		<!-- View Order End -->
	</div>
</section>
</div>
<script>
	let booking = new Vue({
		el:"#viewbooking",
		data() {
			return {
				
			}
		},
	});
</script>
