<?php
namespace Admin\Controller;

use Laminas\Mvc\Controller\AbstractActionController;
use Laminas\Mvc\MvcEvent;
use Laminas\View\Model\ViewModel;

/**
 *
 * @author mac
 *        
 */
class LogisticsConroller extends AbstractActionController
{

    private $entityManager;

    private $generalService;

    public function onDispatch(MvcEvent $e)
    {
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    /**
     * This return a list of all
     * @return ViewModel
     */
    public function indexAction()
    {
        $viewModel = new ViewModel();
        return $viewModel;
    }

    public function upcomingTripAction()
    {

    }

    public function initiatedTripAction()
    {

    }

    public function inTransiTripAction()
    {

        $viewModel = new ViewModel();
        return $viewModel;

    }

    public function canceledAction(){
        $viewmodel = new ViewModel();
        return $viewmodel;
    }

    public function completedAction(){
        $viewmodel = new ViewModel();
        return $viewmodel;
    }
}

