<?php
echo $this->headtitle("Driver Controller");

?>



<div id="driverId">

    <div class="content-inner boxed mt-4 w-100">
        <div class="container">
            <!-- Begin Page Header-->
            <div class="row">
                <div class="page-header">
                    <div class="d-flex align-items-center">
                        <h2 class="page-header-title">Driver : <?php  echo $user->getFullName()?> </h2>
                        <div>
                            <!-- 	                                <div class="page-header-tools"> -->
                            <!-- 	                                    <a class="btn btn-gradient-01" href="#">Add Widget</a> -->
                            <!-- 	                                </div> -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Page Header -->
            <!-- Begin Row -->

            <!-- End Row -->
            <div class="row flex-row">
                

                <div class="col-xl-6 col-md-6 col-sm-12">
                    <!-- Begin Widget 01 -->
                    <div class="widget widget-01 has-shadow">
                        <div class="widget-body no-padding">
                        <h3>Active Booking</h3>
                            <br>
                            <div class="row no-margin justify-content-center">
                                <div class="col-12 col-xl-12 col-md-12 col-sm-10">
                                    <div class="today-sales">
                                    <div class="text">
                                    <br>
                                            <div class="heading">Phone Number</div>
                                            <div class="number">CustomerName</div>
                                            <div class="value text-blue">Email</div>
                                            <hr>
                                            <div class="heading">State : <span></span></div>
                                        </div>
                                        <div class="col-12 widget widget-18">
                                            <div class="new-message">
                                                <div class="media">

                                                    <div class="media-body align-self-center">
                                                        <div class="new-message-sender">Pick Up Address</div>
                                                        <div class="new-message-time"></div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-12 widget widget-18">
                                            <div class="new-message">
                                                <div class="media">

                                                    <div class="media-body align-self-center">
                                                        <div class="new-message-sender">Destination Address</div>
                                                        <div class="new-message-time"></div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        
                                    </div>
                                </div>
                                <!-- End Today Sales -->
                            </div>


                            <div class="circle">

                                <button type="button" class="btn btn-primary btn-lg">Large button</button>
                            </div>
                            <!-- Begin Other Stats -->
                            <div class="other-stats">
                                <!-- Begin Row -->

                                <!-- End Row -->
                            </div>
                            <!-- End Other Stats -->
                        </div>
                    </div>
                    <!-- End Widget 01 -->
                </div>


                <div class="col-xl-6 col-md-6 os-animation" data-os-animation="fadeInUp">
                    <!-- Begin Widget 05 -->
                    <div class="widget widget-05 has-shadow">
                        <!-- Begin Widget Header -->
                        <div class="widget-header bordered d-flex align-items-center">
                            <h2>Top Author</h2>

                        </div>
                        <!-- End Widget Header -->
                        <!-- Begin Widget Body -->
                        <div class="widget-body no-padding hidden">
                            <div class="author-avatar">
                                <span class="badge-pulse-green"></span>
                                

                            </div>
                            <div class="author-name">
                                Louis Henry
                                <span>Designer</span>
                            </div>
                            <div class="chart">
                                <div class="row no-margin justify-content-center">
                                    <div class="col-12 col-xl-8 col-md-8 col-sm-8">
                                        <div class="row no-margin align-items-center">
                                            <!-- Begin Chart -->
                                            <div class="col-9 no-padding">
                                                <div class="chart-graph">
                                                    <div class="chart">
                                                        <canvas id="sales-stats"></canvas>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-3 no-padding text-center">
                                                <div class="chart-text">
                                                    <span class="heading">Sales</span>
                                                    <span class="number">364</span>
                                                    <span class="cxg text-green">+35%</span>
                                                </div>
                                            </div>
                                            <!-- End Chart -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="social-stats">
                                <div class="row d-flex justify-content-between">
                                    <div class="col-4 text-center">
                                        <i class="la la-users followers"></i>
                                        <div class="counter">+124</div>
                                        <div class="heading">Followers</div>
                                    </div>
                                    <div class="col-4 text-center">
                                        <i class="la la-dribbble dribbble"></i>
                                        <div class="counter">+357</div>
                                        <div class="heading">Likes</div>
                                    </div>
                                    <div class="col-4 text-center">
                                        <i class="la la-behance behance"></i>
                                        <div class="counter">+98</div>
                                        <div class="heading">Followers</div>
                                    </div>
                                </div>
                            </div>
                            <div class="actions text-center">
                                <a href="pages-profile.html" class="btn btn-gradient-01">View Profile</a>
                            </div>
                        </div>
                        <!-- End Widget Body -->
                    </div>
                    <!-- End Widget 05 -->
                </div>
            </div>
            <!-- End Row -->
            <div class="row flex-row">
                <div class="col-xl-12 os-animation" data-os-animation="fadeInUp">
                    <!-- Begin Widget 07 -->
                    <div class="widget widget-07 has-shadow">
                        <!-- Begin Widget Header -->
                        <div class="widget-header bordered d-flex align-items-center">
                            <h2>Previous Trips</h2>
                            <!--                                         <div class="widget-options"> -->
                            <!--                                             <div class="btn-group" role="group"> -->
                            <!--                                                 <button type="button" class="btn btn-primary ripple">Week</button> -->
                            <!--                                                 <button type="button" class="btn btn-primary ripple">Month</button> -->
                            <!--                                             </div> -->
                            <!--                                         </div> -->
                        </div>
                        <!-- End Widget Header -->
                        <!-- Begin Widget Body -->
                        <div class="widget-body">
                            <div class="table-responsive table-scroll padding-right-10" style="max-height:520px;">
                                <table class="table table-hover mb-0">
                                    <thead>
                                        <tr>
                                            <th>
                                                <div class="styled-checkbox mt-2">
                                                    <input type="checkbox" name="check-all" id="check-all">
                                                    <label for="check-all"></label>
                                                </div>
                                            </th>
                                            <th>Order ID</th>
                                            <th>Customer Name</th>
                                            <th>Country</th>
                                            <th>Ship Date</th>
                                            <th><span style="width:100px;">Status</span></th>
                                            <th>Order Total</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td style="width:5%;">
                                                <div class="styled-checkbox mt-2">
                                                    <input type="checkbox" name="cb1" id="cb1">
                                                    <label for="cb1"></label>
                                                </div>
                                            </td>
                                            <td><span class="text-primary">054-01-FR</span></td>
                                            <td>Lori Baker</td>
                                            <td>US</td>
                                            <td>10/21/2017</td>
                                            <td><span style="width:100px;"><span class="badge-text badge-text-small info">Paid</span></span></td>
                                            <td>$139.45</td>
                                            <td class="td-actions">
                                                <a href="#"><i class="la la-edit edit"></i></a>
                                                <a href="#"><i class="la la-close delete"></i></a>
                                            </td>
                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- End Widget Body -->
                        <!-- Begin Widget Footer -->
                        <div class="widget-footer d-flex align-items-center">
                            <div class="mr-auto p-2">
                                <span class="display-items">Showing 1-30 / 150 Results</span>
                            </div>
                            <div class="p-2">
                                <nav aria-label="...">
                                    <ul class="pagination justify-content-end">
                                        <li class="page-item disabled">
                                            <span class="page-link"><i class="ion-chevron-left"></i></span>
                                        </li>
                                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                                        <li class="page-item active">
                                            <span class="page-link">2<span class="sr-only">(current)</span></span>
                                        </li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item">
                                            <a class="page-link" href="#"><i class="ion-chevron-right"></i></a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <!-- End Widget Footer -->
                    </div>
                    <!-- End Widget 07 -->
                </div>
            </div>

            <!-- End Row -->
        </div>
        <!-- End Container -->
        <!-- Begin Page Footer-->
        <footer class="main-footer">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-start justify-content-lg-start justify-content-md-start justify-content-center">
                        <p class="text-gradient-02">Design By Saerox</p>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-end justify-content-lg-end justify-content-md-end justify-content-center">
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link" href="documentation.html">Documentation</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="changelog.html">Changelog</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End Page Footer -->
        <a href="#" class="go-top"><i class="la la-arrow-up"></i></a>
        <!-- Offcanvas Sidebar -->
        <div class="off-sidebar from-right">
            <div class="off-sidebar-container">
                <header class="off-sidebar-header">
                    <ul class="button-nav nav nav-tabs mt-3 mb-3 ml-3" role="tablist" id="weather-tab">
                        <li><a class="active" data-toggle="tab" href="#messenger" role="tab" id="messenger-tab">Messages</a></li>
                        <li><a data-toggle="tab" href="#today" role="tab" id="today-tab">Today</a></li>
                    </ul>
                    <a href="#off-canvas" class="off-sidebar-close"></a>
                </header>
                
                <!-- End Offcanvas Container -->
            </div>
            <!-- End Offsidebar Container -->
        </div>
        <!-- End Offcanvas Sidebar -->
    </div>
</div>

<script>
    let driver = new Vue({
        el: "#driverId",
        data() {
            return {
                activetrip:'',
                assignedBooking:""
            }
        },

        mounted() {
            this.getActiveTrip();
            this. getAssignedBooking();
        },

        methods: {
            getDriveringHistory() {

            },

            getActiveTrip(){
                axios.get("/driver/board/active-trip").then(res=>{
                    if(res.status == 200){
                        this.activetrip = res.data.data;
                    }
                }).catch();
            },

            getAssignedBooking(){
                axios.get("/driver/board/assigned-booking").then(res=>{
                    if(res.status == 200){
                        this.assignedBooking = res.data.data;
                    }
                }).catch();
            }

        },
    });
</script>