<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">






</head>

<body>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
    </head>

    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif !important; color: #666666; background:white; text-decoration: none;">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" summary="">
            <tbody>
                <tr align="center">
                    <td style="height: 30px; width: 100%;">
                        &nbsp;
                    </td>
                </tr>
                <tr align="center">
                    <td valign="top" style="width: 100%;">
                        <table cellspacing="0" cellpadding="0" border="0" summary="">
                            <tbody>
                                <tr align="center">
                                    <td valign="middle" style="width: 100%;">
                                        <a href="#" target="_blank"><img width="55" height="71" style="border:0;width:55px;height:71px;" src="<?php echo  $logo ?>" alt="Bau Dispatch"></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr align="center">
                    <td style="height: 50px; width: 100%;">
                        &nbsp;
                    </td>
                </tr>
                <tr align="center">
                    <td valign="top" style="width: 100%;">
                        <table style="padding: 0px; border: 0; max-width: 520px; text-align: center;" width="100%" cellpadding="0" cellspacing="0" border="0" summary="">
                            <tbody>

                                <tr align="center">
                                    <td style="height: 10px; width: 100%;">
                                        &nbsp;
                                    </td>
                                </tr>

                                <tr align="center">
                                    <td style="width: 100%; margin: 0px 10px; line-height: 24px; font-size: 16pt; font-weight: bold; color: #333333;">
                                        <p style="margin: 0; padding: 0;">
                                            You just requested a Dispatch Service
                                        </p>
                                    </td>
                                </tr>
                                <tr align="center">
                                    <td style="height: 5px; width: 100%;">
                                        &nbsp;
                                    </td>
                                </tr>
                                <tr align="center" style="margin: 0px 10px;">
                                    <td style="width: 100%; line-height: 24px; font-size: 13pt;">

                                        <img src="http://baucars.com/3333449.jpeg">
                                    </td>
                                </tr>
                                <tr align="center">
                                    <td style="height: 30px; width: 100%;">
                                        &nbsp;
                                    </td>
                                </tr>

                                <tr>
                                    <td style="height: 40px; width: 100%;">
                                        &nbsp;
                                    </td>
                                </tr>
                                <tr align="center" style="margin: 0px 10px;">
                                    <td style="width: 100%; font-size: 9pt; color: #b3b3b3;">
                                        <p style="line-height: 16px; max-width: 400px;">
                                            <b>What does that mean?</b><br> We have received your request and beginning to process it, a rider would be assigned to you as soon as possible
                                        </p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <table style="border-collapse:collapse; max-width: 520px; text-align: center;" cellpadding="0" cellspacing="0" border="0" summary="">
                            <tbody>
                                <tr>
                                    <td style="height: 80px; width: 100%;">
                                        &nbsp;
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" style="width: 100%;">
                                        <p style="line-height: 20px; font-size: 9pt; color: #b3b3b3;">
                                            <a href="https://baucars.com" style="color: #b3b3b3; text-decoration: underline;" target="_blank">Bau Cars</a><br>Odua Office Complex, Blk 16 Suite 7&8, New garage Ojota Lagos, Nigeria<br><a href="#" style="color: #b3b3b3; text-decoration: underline;" target="_blank">Unsubscribe</a>&nbsp;·&nbsp;

                                        </p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr align="center">
                    <td style="height: 55px; width: 100%;">
                        &nbsp;
                    </td>
                </tr>
            </tbody>
        </table>


    </body>


</body>

</html>