<div id="board">
	<section class="page--header">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6">
					<!-- Page Title Start -->
					<h2 class="page--title h5">Dashboard</h2>
					<!-- Page Title End -->

					<ul class="breadcrumb">
						<li class="breadcrumb-item active"><span>Dashboard</span></li>
					</ul>
				</div>


			</div>
		</div>
	</section>
	<section class="main--content">
		<div class="row gutter-20">
			<div class="col-md-4">
				<div class="panel">
					<!-- Mini Stats Panel Start -->
					<div class="miniStats--panel">
						<div class="miniStats--header bg-darker">
							<!-- 								<p class="miniStats--chart" data-trigger="sparkline" -->
							<!-- 									data-type="bar" data-width="4" data-height="30" -->
							<!-- 									data-color="#2bb3c0">5,6,9,4,9,5,3,5,9,15,3,2,2,3,9,11,9,7,20,9,7,6</p> -->

							<p class="miniStats--label text-white bg-blue">
								<!-- 									<i class="fa fa-level-up-alt"></i> <span>10%</span> -->
							</p>
						</div>

						<div class="miniStats--body">
							<i class="miniStats--icon fa fa-user text-blue"></i>

							<!-- 								<p class="miniStats--caption text-blue">Monthly</p> -->
							<h3 class="miniStats--title h4">TOTAL CUSTOMERS</h3>
							<p class="miniStats--num text-blue">{{customers}}</p>
						</div>
					</div>
					<!-- Mini Stats Panel End -->
				</div>
			</div>

			<div class="col-md-4">
				<div class="panel">
					<!-- Mini Stats Panel Start -->
					<div class="miniStats--panel">
						<div class="miniStats--header bg-darker">
							<!-- 								<p class="miniStats--chart" data-trigger="sparkline" -->
							<!-- 									data-type="bar" data-width="4" data-height="30" -->
							<!-- 									data-color="#e16123">2,2,3,9,11,9,7,20,9,7,6,5,6,9,4,9,5,3,5,9,15,3</p> -->

							<p class="miniStats--label text-white bg-orange">
								<!-- 									<i class="fa fa-level-down-alt"></i> <span>10%</span> -->
							</p>
						</div>

						<div class="miniStats--body">
							<i class="miniStats--icon fa fa-ticket-alt text-orange"></i>

							<!-- 								<p class="miniStats--caption text-orange">Monthly</p> -->
							<h3 class="miniStats--title h4">INITIATED BOOKING</h3>
							<p class="miniStats--num text-orange">{{initiatedBooking}}</p>
						</div>
					</div>
					<!-- Mini Stats Panel End -->
				</div>
			</div>

			<div class="col-md-4">
				<div class="panel">
					<!-- Mini Stats Panel Start -->
					<div class="miniStats--panel">
						<div class="miniStats--header bg-darker">
							<!-- 								<p class="miniStats--chart" data-trigger="sparkline" -->
							<!-- 									data-type="bar" data-width="4" data-height="30" -->
							<!-- 									data-color="#009378">2,2,3,9,11,9,7,20,9,7,6,5,6,9,4,9,5,3,5,9,15,3</p> -->

							<p class="miniStats--label text-white bg-green">
								<!-- 									<i class="fa fa-level-up-alt"></i> <span>10%</span> -->
							</p>
						</div>

						<div class="miniStats--body">
							<i class="miniStats--icon fa fa-rocket text-green"></i>

							<!-- 								<p class="miniStats--caption text-green">Monthly</p> -->
							<h3 class="miniStats--title h4">ACTIVE TRIP</h3>
							<p class="miniStats--num text-green">{{activeTrip}}</p>
						</div>
					</div>
					<!-- Mini Stats Panel End -->
				</div>
			</div>

			<!-- 			<div class="col-xl-8 col-md-6"> -->
			<!-- 				<div class="panel"> -->
			<!-- 					<div class="panel-heading"> -->
			<!-- 						<h3 class="panel-title">Yearly Earning Graph Overview</h3> -->

			<!-- 						<div class="dropdown"> -->
			<!-- 							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown"> -->
			<!-- 								<i class="fa fa-ellipsis-v"></i> -->
			<!-- 							</button> -->

			<!-- 							<ul class="dropdown-menu"> -->
			<!-- 								<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li> -->
			<!-- 								<li><a href="#"><i class="fa fa-cogs"></i>Settings</a></li> -->
			<!-- 								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li> -->
			<!-- 							</ul> -->
			<!-- 						</div> -->
			<!-- 					</div> -->

			<!-- 					<div class="panel-chart"> -->
			<!-- Morris Area Chart 01 Start -->
			<!-- 						<div id="morrisAreaChart01" class="chart--body area--chart style--1"></div> -->
			<!-- Morris Area Chart 01 End -->

			<!-- 						<div class="chart--stats style--1"> -->
			<!-- 							<ul class="nav"> -->
			<!-- 								<li data-overlay="1 orange"> -->
			<!-- 									<p class="amount">$10,320,340</p> -->
			<!-- 									<p> -->
			<!-- 										<span class="label">Order</span> <span class="text-red"><i class="fa fa-long-arrow-alt-down"></i>2.25%</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 								<li data-overlay="1 red"> -->
			<!-- 									<p class="amount">$235,090</p> -->
			<!-- 									<p> -->
			<!-- 										<span class="label">Shipment</span> <span class="text-green"><i class="fa fa-long-arrow-alt-up"></i>2.25%</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 								<li data-overlay="1 blue"> -->
			<!-- 									<p class="amount">$134,900</p> -->
			<!-- 									<p> -->
			<!-- 										<span class="label">Tax</span> <span class="text-red"><i class="fa fa-long-arrow-alt-down"></i>2.25%</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 								<li data-overlay="1 green"> -->
			<!-- 									<p class="amount">$1,340</p> -->
			<!-- 									<p> -->
			<!-- 										<span class="label">Revenue</span> <span class="text-green"><i class="fa fa-long-arrow-alt-up"></i>2.25%</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 							</ul> -->
			<!-- 						</div> -->
			<!-- 					</div> -->
			<!-- 				</div> -->
			<!-- 			</div> -->

			<!-- 			<div class="col-xl-4 col-md-6"> -->
			<!-- 				<div class="panel"> -->
			<!-- 					<div class="panel-heading"> -->
			<!-- 						<h3 class="panel-title">Market Trends</h3> -->

			<!-- 						<div class="dropdown"> -->
			<!-- 							<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown"> -->
			<!-- 								<i class="fa fa-ellipsis-v"></i> -->
			<!-- 							</button> -->

			<!-- 							<ul class="dropdown-menu"> -->
			<!-- 								<li><a href="#">This Week</a></li> -->
			<!-- 								<li><a href="#">Last Week</a></li> -->
			<!-- 							</ul> -->
			<!-- 						</div> -->
			<!-- 					</div> -->

			<!-- 					<div class="panel-chart"> -->
			<!-- Morris Area Chart 02 Start -->
			<!-- 						<div id="morrisAreaChart02" class="chart--body area--chart style--1"></div> -->
			<!-- Morris Area Chart 02 End -->

			<!-- 						<div class="chart--stats style--2"> -->
			<!-- 							<ul class="nav"> -->
			<!-- 								<li> -->
			<!-- 									<p class="amount">$56,700</p> -->
			<!-- 									<p data-overlay="1 blue"> -->
			<!-- 										<span class="label">TOTAL EQUITY</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 								<li> -->
			<!-- 									<p class="amount">$4,000</p> -->
			<!-- 									<p data-overlay="1 red"> -->
			<!-- 										<span class="label">TOTAL DEBT</span> -->
			<!-- 									</p> -->
			<!-- 								</li> -->
			<!-- 							</ul> -->
			<!-- 						</div> -->
			<!-- 					</div> -->
			<!-- 				</div> -->
			<!-- 			</div> -->



			<div class="col-xl-9">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">INITIATED BOOKING</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle"
								data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>


						</div>
					</div>

					<div class="panel-body">
						<div class="table-responsive">
							<table class="table style--2">
								<thead>
									<tr>
										<th>TRACKING ID</th>
										<th>ACTIVE PERIOD</th>
										<!-- <th>AMOUNT PAID</th> -->
										<th>BOOKING CLASS</th>
										<th>BOOKING TYPE</th>
										<th>STATUS</th>
										<th>ACTION</th>
									</tr>
								</thead>
								<tbody>
									<!-- Table Row Start -->
									<tr v-for="data in splashInitiatedBooking ">
										<!-- <td><img src="assets/img/products/thumb-01.jpg" alt=""></td> -->
										<td>{{data.bookingUid.toUpperCase()}}</td>
										<td><a href="#" class="btn-link">{{formatPHPDate(data.startTime.date)}}
												- {{formatPHPDate(data.endTime.date)}}</a></td>
										<td>{{data.bookingClass.bookingClass}}</td>
										<td>{{data.bookingType.bookingType}}</td>
										<td><span class="label label-success">{{data.status.status}}</span></td>
										<td><a :href="initiateBookingListLink(data.bookingUid)"><i
												class="fa fa-eye"></i></a></td>
									</tr>
									<!-- Table Row End -->


								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<div class="col-xl-3">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">To-Do List</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle"
								data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>

							<ul class="dropdown-menu">
								<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
							</ul>
						</div>
					</div>

					<div class="todo--panel">
						<form action="#">
							<ul class="list-group" data-trigger="scrollbar">
								<li class="list-group-item"><label class="todo--label"> <input
										type="checkbox" name="todo_id" value="1" class="todo--input"
										checked> <span class="todo--text">Schedule Meeting</span>
								</label> <a href="#" class="todo--remove">&times;</a></li>
								<li class="list-group-item"><label class="todo--label"> <input
										type="checkbox" name="todo_id" value="2" class="todo--input">
										<span class="todo--text">Call Clients To Follow-Up</span>
								</label> <a href="#" class="todo--remove">&times;</a></li>
								<li class="list-group-item"><label class="todo--label"> <input
										type="checkbox" name="todo_id" value="3" class="todo--input"
										checked> <span class="todo--text">Book Flight For Holiday</span>
								</label> <a href="#" class="todo--remove">&times;</a></li>
								<li class="list-group-item"><label class="todo--label"> <input
										type="checkbox" name="todo_id" value="4" class="todo--input">
										<span class="todo--text">Forward Important Tasks</span>
								</label> <a href="#" class="todo--remove">&times;</a></li>
								<li class="list-group-item"><label class="todo--label"> <input
										type="checkbox" name="todo_id" value="6" class="todo--input">
										<span class="todo--text">Important Tasks</span>
								</label> <a href="#" class="todo--remove">&times;</a></li>
							</ul>

							<div class="input-group">
								<input type="text" name="todo" placeholder="Add New Task"
									class="form-control" autocomplete="off" required>

								<div class="input-group-btn">
									<button type="submit" class="btn-link">+</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>

			<div class="col-xl-9">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">IN TRANSIT</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle"
								data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>


						</div>
					</div>

					<div class="panel-body">
						<div class="table-responsive">
							<table class="table style--2">
								<thead>
									<tr>
										<th>Product Image</th>
										<th>Product ID</th>
										<th>Customer Name</th>
										<th>Price</th>
										<th>Quantity</th>
										<th>Tracking No.</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									<!-- Table Row Start -->
									<tr>
										<td><img src="assets/img/products/thumb-01.jpg" alt=""></td>
										<td>3BSD59</td>
										<td><a href="#" class="btn-link">Leisure Suit Casual</a></td>
										<td>$99</td>
										<td>2</td>
										<td><span class="text-muted">#BG6R9853lP</span></td>
										<td><span class="label label-success">Paid</span></td>
									</tr>
									<!-- Table Row End -->

									<!-- Table Row Start -->
									<tr>
										<td><img src="assets/img/products/thumb-02.jpg" alt=""></td>
										<td>3BSD59</td>
										<td><a href="#" class="btn-link">Leisure Suit Casual</a></td>
										<td>$99</td>
										<td>2</td>
										<td><span class="text-muted">#BG6R9853lP</span></td>
										<td><span class="label label-warning">Due</span></td>
									</tr>
									<!-- Table Row End -->

									<!-- Table Row Start -->
									<tr>
										<td><img src="assets/img/products/thumb-03.jpg" alt=""></td>
										<td>3BSD59</td>
										<td><a href="#" class="btn-link">Leisure Suit Casual</a></td>
										<td>$99</td>
										<td>2</td>
										<td><span class="text-muted">#BG6R9853lP</span></td>
										<td><span class="label label-info">Rejected</span></td>
									</tr>
									<!-- Table Row End -->
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<div class="col-xl-3 col-md-6">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Total Overdue</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle"
								data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>

							<ul class="dropdown-menu">
								<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
								<li><a href="#"><i class="fa fa-cogs"></i>Settings</a></li>
								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
							</ul>
						</div>
					</div>

					<div class="panel-chart">
						<div class="chart--title text-blue">
							<h2 class="h2">$14,200,000</h2>
						</div>

						<!-- Morris Line Chart 03 Start -->
						<div id="morrisLineChart03"
							class="chart--body line--chart style--3"></div>
						<!-- Morris Line Chart 03 End -->

						<div class="chart--action">
							<a href="#" class="btn-link">Export PDF <i
								class="fa fa-long-arrow-right"></i></a>
						</div>
					</div>
				</div>
			</div>



<div class="col-xl-9">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">CANCELED  BOOKING</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle"
								data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>


						</div>
					</div>

					<div class="panel-body">
						<div class="table-responsive">
							<table class="table style--2">
								<thead>
									<tr>
										<th>Product Image</th>
										<th>Product ID</th>
										<th>Customer Name</th>
										<th>Price</th>
										<th>Quantity</th>
										<th>Tracking No.</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									<!-- Table Row Start -->
									<tr>
										<td><img src="assets/img/products/thumb-01.jpg" alt=""></td>
										<td>3BSD59</td>
										<td><a href="#" class="btn-link">Leisure Suit Casual</a></td>
										<td>$99</td>
										<td>2</td>
										<td><span class="text-muted">#BG6R9853lP</span></td>
										<td><span class="label label-success">Paid</span></td>
									</tr>
									<!-- Table Row End -->

									<!-- Table Row Start -->
									<tr>
										<td><img src="assets/img/products/thumb-02.jpg" alt=""></td>
										<td>3BSD59</td>
										<td><a href="#" class="btn-link">Leisure Suit Casual</a></td>
										<td>$99</td>
										<td>2</td>
										<td><span class="text-muted">#BG6R9853lP</span></td>
										<td><span class="label label-warning">Due</span></td>
									</tr>
									<!-- Table Row End -->

									<!-- Table Row Start -->
									<tr>
										<td><img src="assets/img/products/thumb-03.jpg" alt=""></td>
										<td>3BSD59</td>
										<td><a href="#" class="btn-link">Leisure Suit Casual</a></td>
										<td>$99</td>
										<td>2</td>
										<td><span class="text-muted">#BG6R9853lP</span></td>
										<td><span class="label label-info">Rejected</span></td>
									</tr>
									<!-- Table Row End -->
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<div class="col-xl-3 col-md-6">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Total Overdue</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle"
								data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>

							<ul class="dropdown-menu">
								<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
								<li><a href="#"><i class="fa fa-cogs"></i>Settings</a></li>
								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
							</ul>
						</div>
					</div>

					<div class="panel-chart">
						<div class="chart--title text-blue">
							<h2 class="h2">$14,200,000</h2>
						</div>

						<!-- Morris Line Chart 03 Start -->
						<div id="morrisLineChart03"
							class="chart--body line--chart style--3"></div>
						<!-- Morris Line Chart 03 End -->

						<div class="chart--action">
							<a href="#" class="btn-link">Export PDF <i
								class="fa fa-long-arrow-right"></i></a>
						</div>
					</div>
				</div>
			</div>





			

			

			

			<div class="col-xl-6">
				<div class="panel">
					<div class="profile--panel">
						<div class="img-wrapper"
							data-bg-img="assets/img/covers/01_800x150.jpg">
							<div class="img online">
								<img src="assets/img/avatars/01_150x150.png" alt=""
									class="rounded-circle">
							</div>
						</div>

						<div class="name">
							<h3 class="h3">Henry Foster</h3>
						</div>

						<div class="role">
							<p>Web Developer &amp; Graphic Designer</p>
						</div>

						<div class="action">
							<a href="#" class="btn btn-info">+ Follow</a>
						</div>

						<div class="bio">
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo
								ratione vitae aliquid aliquam provident nostrum itaque quam
								minima molestias.</p>
						</div>

						<ul class="info nav text-uppercase">
							<li><strong>1125</strong> <span>Items</span></li>
							<li><strong>133</strong> <span>Projects</span></li>
							<li><strong>3025</strong> <span>Followers</span></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="col-xl-3 col-md-6">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Feeds &amp; Activities</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle"
								data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>

							<ul class="dropdown-menu">
								<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
							</ul>
						</div>
					</div>

					<div class="feeds-panel">
						<ul class="nav">
							<li><span class="time">2 mins</span> <i
								class="fa fa-shopping-cart text-white bg-blue"></i> <span
								class="text">New Order Received</span></li>
							<li><span class="time">10 mins</span> <i
								class="fa fa-user text-white bg-orange"></i> <span class="text">Updated
									Profile Picture</span></li>
							<li><span class="time">20 mins</span> <i
								class="fa fa-comment text-white bg-red"></i> <span class="text"><a
									href="#">John Doe</a> Commented on <a href="#">News #123</a></span>
							</li>
							<li><span class="time">21 mins</span> <i
								class="fa fa-shopping-cart text-white bg-blue"></i> <span
								class="text">New Order Received</span></li>
							<li><span class="time">25 mins</span> <i
								class="fa fa-user text-white bg-green"></i> <span class="text">New
									User Registered</span></li>
							<li><span class="time">25 mins</span> <i
								class="fa fa-times text-white bg-dark"></i> <span class="text">Order
									<a href="#">#24DP01</a> Rejected
							</span></li>
							<li><span class="time">2 hours</span> <i
								class="fa fa-comment text-white bg-red"></i> <span class="text"><a
									href="#">John Doe</a> Commented on <a href="#">News #123</a></span>
							</li>
							<li><span class="time">3 hours</span> <i
								class="fa fa-user text-white bg-orange"></i> <span class="text">You
									Uploaded A Image</span></li>
							<li><span class="time">4 hours</span> <i
								class="fa fa-shopping-cart text-white bg-blue"></i> <span
								class="text">New Order Received</span></li>
							<li><span class="time">8 hours</span> <i
								class="fa fa-user text-white bg-green"></i> <span class="text">New
									User Registered</span></li>
							<li><span class="time">22 hours</span> <i
								class="fa fa-shopping-cart text-white bg-blue"></i> <span
								class="text">New Order Received</span></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="col-xl-3 col-md-6">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Comments</h3>

						<div class="dropdown">
							<button type="button" class="btn-link dropdown-toggle"
								data-toggle="dropdown">
								<i class="fa fa-ellipsis-v"></i>
							</button>

							<ul class="dropdown-menu">
								<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
								<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
							</ul>
						</div>
					</div>

					<div class="comments-panel">
						<ul>
							<li>
								<div class="img">
									<img src="assets/img/avatars/02_40x40.png" alt=""
										class="rounded-circle">
								</div>

								<div class="info">
									<h3 class="h6">John Doe</h3>

									<p>Lorem ipsum dolor sit elit, sed do eiusmod tempor.</p>

									<div class="action">
										<span class="status text-orange">Pending</span> <a href="#"
											class="btn btn-sm btn-info">Delete</a>
									</div>
								</div>
							</li>
							<li>
								<div class="img">
									<img src="assets/img/avatars/03_40x40.png" alt=""
										class="rounded-circle">
								</div>

								<div class="info">
									<h3 class="h6">Jane Doe</h3>

									<p>Lorem ipsum dolor sit elit, sed do eiusmod tempor.</p>

									<div class="action">
										<span class="status text-blue">Approved</span> <a href="#"
											class="btn btn-sm btn-info">Delete</a>
									</div>
								</div>
							</li>
							<li>
								<div class="img">
									<img src="assets/img/avatars/04_40x40.png" alt=""
										class="rounded-circle">
								</div>

								<div class="info">
									<h3 class="h6">Harry Johnson</h3>

									<p>Lorem ipsum dolor sit elit, sed do eiusmod tempor.</p>

									<div class="action">
										<span class="status text-red">Rejected</span> <a href="#"
											class="btn btn-sm btn-info">Delete</a>
									</div>
								</div>
							</li>
						</ul>

						<div class="nav">
							<a href="#" class="next btn-link">Older Comments <i
								class="fa fa-angle-double-right"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
<script>
	let dashboard = new Vue({
		el: "#board",
		mounted() {
			this.getCustomerCount();
			this.getIntiTedBookingCount();
			this.getSplashInitiatedBooking();
		},
		data() {
			return {
				customers: 0,
				initiatedBooking:0,
				activeTrip:0,

				splashInitiatedBooking: [],
			}
		},
		methods: {
			formatPHPDate(date) {
				myDate = date.replace(/-/g, "/");
				return new Date(myDate);
			},

			initiateBookingListLink(uid){
				return "/controller/booking/view/"+uid
			},

			getCustomerCount(){
				axios.get('/controller/customer/allcustomercount').then(res=>{
					if(res.status == 200){
						this.customers = res.data.count;
					}
				}).catch();
			},

			getIntiTedBookingCount(){
				axios.get("/controller/booking/initiatedbookingcount").then(res=>{
					if(res.status == 200){
						this.initiatedBooking = res.data.count;
					}
				}).catch();
			},

			getActiveTripCount(){

			},

			// Splassh Data
			getSplashInitiatedBooking(){
				axios.get("/controller/booking/splashinitiatedbooking").then(res=>{
					if(res.status == 200){
						this.splashInitiatedBooking = res.data.data;
					}
				}).catch();
			},
		},
	});
</script>