<?php
?>

<div class="col-xl-3">
	<div class="panel">
		<div class="panel-heading">
			<h3 class="panel-title">MENU</h3>

		</div>

		<div class="todo--panel">
			<form action="#">
				<ul class="list-group" data-trigger="scrollbar">
				
				<li class="list-group-item"><a href=""><label class="todo--label">
								<span>All Booking</span>
						</label> </a></li>

					<li class="list-group-item"><a href=""><label class="todo--label">
								<span>Initiated Booking</span>
						</label> </a></li>
					<li class="list-group-item"><a href=""><label class="todo--label">
								<span>Active Trip</span>
						</label> </a></li>
					<li class="list-group-item"><a href=""> <label class="todo--label">
								<span>Canceled Booking </span>
						</label>
					</a></li>

				</ul>


			</form>
		</div>
	</div>
</div>