<?php

?>

<div class="col-xl-3">
	<div class="panel">
		<div class="panel-heading">
			<h3 class="panel-title">To-Do List</h3>

			<div class="dropdown">
				<button type="button" class="btn-link dropdown-toggle" data-toggle="dropdown">
					<i class="fa fa-ellipsis-v"></i>
				</button>

				<ul class="dropdown-menu">
					<li><a href="#"><i class="fa fa-sync"></i>Update Data</a></li>
					<li><a href="#"><i class="fa fa-times"></i>Remove Panel</a></li>
				</ul>
			</div>
		</div>

		<div class="todo--panel">
			<form action="#">
				<ul class="list-group" data-trigger="scrollbar">
					<li class="list-group-item"><label class="todo--label"> <span>Initiated Booking</span>
						</label> </li>
					<li class="list-group-item"><a href=""><label class="todo--label">
							<span>Active Trip</span>
						</label> </a></li>
					<li class="list-group-item"><a href=""> <label class="todo--label"> <span>Canceled Booking </span>
							</label> </a></li>

				</ul>


			</form>
		</div>
	</div>
</div>