<?php
echo $this->headtitle("Customer Board");

?>
<?php
$flashMessenger = $this->flashMessenger()
	->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
	->setMessageSeparatorString('</li><li>')
	->setMessageCloseString('</li></ul></div>');
?>
<?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
<?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
<?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
<?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>

<div class="page-content" id="cutomerPage">

	<div class="content-inner boxed mt-4 w-100">
		<div class="container">


			<div class="row">
				<div class="page-header mt-3">
					<div class="row d-flex align-items-center">
						<div class="col-xl-6 col-lg-6 col-md-6 col-12 d-flex justify-content-xl-end justify-content-lg-end justify-content-md-end justify-content-center">
							<h2 class="page-header-title" style="margin-right: 0 !important;"> Welcome {{profileName}}</h2>
						</div>
						<!-- <div class="col-xl-6 col-lg-6 col-md-6 col-12 d-flex justify-content-xl-start justify-content-lg-start justify-content-md-start justify-content-center">
							<div class="page-header-tools">
								<a class="btn btn-gradient-01" @click="toggleBookingForm()"> Book a Ride</a>
							</div>
						</div> -->
					</div>
				</div>
			</div>









			<div class="row flex-row">
				<div class="col-xl-6  os-animation" data-os-animation="fadeInUp">
					<!-- Begin Widget 05 -->
					<div class="widget widget-05 has-shadow">
						<!-- Begin Widget Header -->
						<div class="widget-header bordered d-flex align-items-center">
							<h2>Booking Form</h2>
							<div class="widget-options">
								<div class="dropdown">
									<button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle">
										<i class="la la-ellipsis-h"></i>
									</button>

								</div>
							</div>
						</div>
						<!-- End Widget Header -->
						<!-- Begin Widget Body -->
						<div class="widget-body no-padding hidden">

							<div class="row flex-row">
								<div class="col-xl-12">
									<!-- Form -->

									<div class="widget has-shadow">



										<div class="widget-body">
											<form class="needs-validation" novalidate>


												<div v-if="bookingServiceType.length" class="form-group row d-flex align-items-center mb-5">
													<label class="col-lg-4 form-control-label d-flex justify-content-lg-end">Booking Service *</label>
													<div class="col-lg-8">
														<div class="select">
															<select v-model="selectedServiceType" class="custom-select form-control" required>

																<option v-for="type in bookingServiceType" :value="type.id">{{type.bookingType}}</option>

															</select>
															<!-- <div class="invalid-feedback">
																Please select an option
															</div> -->
														</div>
													</div>
												</div>




												<div v-if="billingMethod.length" class="form-group row d-flex align-items-center mb-5">
													<label class="col-lg-4 form-control-label d-flex justify-content-lg-end">Billing Method</label>
													<div class="col-sm-8">
														<div v-for="(type, key) in billingMethod" class="mb-3">
															<!-- <div class="styled-radio"> -->
															<input @click="getVal(type.id)" :value="type.id" :key="type.id" v-model="selectedBillingMethod" type="radio" name="radio">
															<label for="rad-1">{{type.billingMethod}}</label>
															<!-- </div> -->
														</div>


													</div>
												</div>


												<div v-if="bookingClass.length" class="form-group row d-flex align-items-center mb-5">
													<label class="col-lg-4 form-control-label d-flex justify-content-lg-end">Service Class *</label>
													<div class="col-lg-8">
														<div class="select">
															<select v-model="selectedBookingClass" class="custom-select form-control" required>

																<option v-for="type in bookingClass" :value="type.id">{{type.bookingClass}}</option>

															</select>
															<!-- <div class="invalid-feedback">
																Please select an option
															</div> -->
														</div>
													</div>
												</div>


												<div class="form-group row d-flex align-items-center mb-5">
													<label class="col-lg-4 form-control-label d-flex justify-content-lg-end">Booking Time</label>
													<div class="col-lg-8">
														<input type="text" ref="bookingDatetime" id="datetime" class="form-control" placeholder="">
													</div>
												</div>


												<div v-if="processing">

													<div class="spinner"></div>
												</div>
												<div v-else>
													<div v-if="bookingPrice != '' ">
														<div class="widget widget-16 has-shadow">
															<div class="widget-body">
																<div class="row">
																	<div class="col-xl-8 d-flex flex-column justify-content-center align-items-center">
																		<div class="counter">&#8358; {{bookingPrice}}</div>
																		<!-- <div class="total-views"></div> -->
																	</div>
																	<div class="col-xl-4 d-flex justify-content-center align-items-center">
																		<div class="pages-views">
																			<div class="percent"></div>
																		</div>
																	</div>
																</div>
															</div>
														</div>

													</div>
													<div class="text-right">
														<button v-if="bookingPrice != ''" @click="makePayment()" :disabled="isSubmittingBookingForm" class="btn  btn-success" type="button">Make PAYMENT</button>

														<button @click="calculatePrice()" :disabled="isSubmittingBookingForm" class="btn btn-gradient-01" type="button">Calculate Price</button>

														<button class="btn btn-shadow" type="reset">Reset</button>
													</div>
												</div>
											</form>


										</div>
									</div>
									<!-- End Form -->
								</div>
							</div>

						</div>

						<!-- End Widget Body -->
					</div>
					<!-- End Widget 05 -->
				</div>




				<div class="col-xl-6 os-animation" data-os-animation="fadeInUp">
					<!-- Begin Widget 06 -->
					<div class="widget widget-05 has-shadow">
						<!-- Begin Widget Header -->
						<div class="widget-header bordered d-flex align-items-center">
							<h2> My Profile</h2>
							<div class="widget-options">
								<div class="dropdown">
									<button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle">
										<i class="la la-ellipsis-h"></i>
									</button>

								</div>
							</div>
						</div>
						<!-- End Widget Header -->
						<!-- Begin Widget Body -->

						<div class="widget-body no-padding hidden">

							<div class="author-avatar">
								<span class="badge-pulse-green"></span> <img src="/img/avatar.png" alt="..." class="img-fluid rounded-circle">
							</div>
							<div class="author-name">
								{{profileName}} <span>{{profileEmail}}</span>
							</div>
							<div class="chart">
								<div class="row no-margin justify-content-center">
									<div class="col-12 col-xl-8 col-md-8 col-sm-8">
										<div class="row no-margin align-items-center">
											<!-- Begin Chart -->
											<div class="col-9 no-padding">
												<div class="chart-graph">
													<div class="chart">
														<canvas id="sales-stats"></canvas>
													</div>
												</div>
											</div>

											<!-- End Chart -->
										</div>
									</div>
								</div>
							</div>


						</div>
						<!-- End Widget Body -->
					</div>
					<!-- End Widget 06 -->
				</div>
			</div>







			<div class="row flex-row">


				<div class="col-xl-6  os-animation" data-os-animation="fadeInUp">
					<div class="col-xl-12 os-animation" data-os-animation="fadeInUp">
						<!-- Begin Widget 07 -->
						<div class="widget widget-07 has-shadow">
							<!-- Begin Widget Header -->
							<div class="widget-header bordered d-flex align-items-center">
								<h2>ACTIVE TRIP</h2>

							</div>
							<!-- End Widget Header -->
							<!-- Begin Widget Body -->

							<div class="widget-body">
								<div class="table-responsive table-scroll padding-right-10" style="max-height: 520px;">
									<table class="table table-hover mb-0">
										<thead>
											<tr>



												<th>Booking Date/Time</th>
												<th>Ship Date</th>
												<th>Status</th>
												<th>Amount Paid</th>
												<th>Actions</th>
											</tr>
										</thead>
										<tbody>
											<tr v-if="initializedBooking.length" v-for="booking in initializedBooking">

												<!-- <td><span class="text-primary">{{booking.bookingUid.toUpperCase()}}</span></td> -->
												<!-- <td></td> -->
												<td>{{formatPHPDate(booking.startTime.date)}}</td>
												<td>{{formatPHPDate(booking.endTime.date)}}</td>
												<td><span style='width:100px;'><span :class='bookingStatus(booking.status.id)'> {{booking.status.status}} </span></span></td>
												<td>&#8358;{{formatPrice(booking.transaction.amount)}}</td>
												<td class="td-actions"> <a href="#"><i class="la la-close delete"></i></a></td>
											</tr>






										</tbody>
									</table>
								</div>
							</div>
							<!-- End Widget Body -->

						</div>
						<!-- End Widget 07 -->
					</div>

				</div>







				<div class="col-xl-6 os-animation" data-os-animation="fadeInUp">
					<!-- Begin Widget 06 -->
					<div class="col-xl-12 os-animation" data-os-animation="fadeInUp">
						<!-- Begin Widget 07 -->
						<div class="widget widget-07 has-shadow">
							<!-- Begin Widget Header -->
							<div class="widget-header bordered d-flex align-items-center">
								<h2>INITIALIZED BOOKING</h2>

							</div>
							<!-- End Widget Header -->
							<!-- Begin Widget Body -->

							<div class="widget-body">
								<div class="table-responsive table-scroll padding-right-10" style="max-height: 520px;">
									<table class="table table-hover mb-0">
										<thead>
											<tr>



												<th>Booking Date/Time</th>
												<th>Ship Date</th>
												<th>Status</th>
												<th>Amount Paid</th>
												<th>Actions</th>
											</tr>
										</thead>
										<tbody>
											<tr v-if="initializedBooking.length" v-for="booking in initializedBooking">

												<!-- <td><span class="text-primary">{{booking.bookingUid.toUpperCase()}}</span></td> -->
												<!-- <td></td> -->
												<td>{{formatPHPDate(booking.startTime.date)}}</td>
												<td>{{formatPHPDate(booking.endTime.date)}}</td>
												<td><span style='width:100px;'><span :class='bookingStatus(booking.status.id)'> {{booking.status.status}} </span></span></td>
												<td>&#8358;{{formatPrice(booking.transaction.amount)}}</td>
												<td class="td-actions"> <a href="#"><i class="la la-close delete"></i></a></td>
											</tr>






										</tbody>
									</table>
								</div>
							</div>
							<!-- End Widget Body -->

						</div>
						<!-- End Widget 07 -->
					</div>
				</div>



			</div>









			<!-- End Row -->
			<div class="row flex-row" v-if="!gettingBookingHistory">
				<div class="col-xl-12 os-animation" data-os-animation="fadeInUp">
					<!-- Begin Widget 07 -->
					<div class="widget widget-07 has-shadow">
						<!-- Begin Widget Header -->
						<div class="widget-header bordered d-flex align-items-center">
							<h2>Booking </h2>

						</div>
						<!-- End Widget Header -->
						<!-- Begin Widget Body -->

						<div class="widget-body">
							<div class="table-responsive table-scroll padding-right-10" style="max-height: 520px;">
								<table class="table table-hover mb-0">
									<thead>
										<tr>

											<th>Order ID</th>
											<th>Booking Type</th>
											<th>Booking Class</th>
											<th>Start Date</th>
											<th>End Date</th>
											<th><span style="width: 100px;">Status</span></th>
											<th>Amount Paid</th>
											<th>Actions</th>
										</tr>
									</thead>
									<tbody>
										<tr v-if="bookingHistory.length" v-for="booking in bookingHistory">

											<td><span class="text-primary">{{booking.bookingUid}}</span></td>
											<td>{{booking.bookingType.bookingType}}</td>
											<td>{{booking.bookingClass.bookingClass}}</td>
											<td>{{formatPHPDate(booking.startTime.date)}}</td>
											<td>{{formatPHPDate(booking.endTime.date)}}</td>
											<td><span style="width: 100px;"><span :class='bookingStatus(booking.status.id)'> {{booking.status.status}} </span></span></td>
											<td>&#8358;{{formatPrice(booking.transaction.amount)}}</td>
											<td class="td-actions"><a href="#"><i class="la la-edit edit"></i></a> <a @click="onCancelBooking(booking.id)" href="#"><i class="la la-close delete"></i></a></td>
										</tr>


									</tbody>
								</table>
							</div>
						</div>
						<!-- End Widget Body -->

					</div>
					<!-- End Widget 07 -->
				</div>
			</div>
			
			<div class="row flex-row">
				<div class="col-xl-6  os-animation" data-os-animation="fadeInUp">
					<!-- Begin Widget 04 -->
					<div class="widget widget-04 has-shadow">
						<!-- Begin Widget Header -->
						<div class="widget-header bordered d-flex align-items-center">
							<h2>Support Tickets</h2>
							<div class="widget-options">
								<div class="dropdown">
									<button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle">
										<i class="la la-ellipsis-h"></i>
									</button>
									<!-- <div class="dropdown-menu">
										<a href="#" class="dropdown-item">
											<i class="la la-check"></i>Valid Post
										</a>
										<a href="#" class="dropdown-item">
											<i class="la la-edit"></i>Edit Widget
										</a>
										<a href="faq.html" class="dropdown-item faq">
											<i class="la la-question-circle"></i>FAQ
										</a>
									</div> -->
								</div>
							</div>
						</div>
						<!-- End Widget Header -->
						<!-- Begin Widget Body -->
						<div class="widget-body p-0">
							<div class="post-container">

								<div class="widget-body no-padding">
									<ul class="ticket list-group w-100">
										<!-- 01 -->
										<div v-if="supportTickets.length">
											<li v-for="ticket in supportTickets" class="list-group-item">
												<div class="media">

													<div class="media-body align-self-center">
														<div class="username">
															<h4></h4>
														</div>

														<div class="status">
															<span class="open mr-2">Open</span>
														</div>
													</div>
												</div>
											</li>
										</div>
										<!-- End 01 -->
										<li v-else class="list-group-item">
											<div class="media">

												No Ticket
											</div>
										</li>
									</ul>
								</div>

							</div>
							<!-- Begin Write Comment -->
							<div class="input-group mt-5">
								<button class="btn btn-primary btn-block"> OPEN TICKETS</button>
							</div>
							<!-- End Write Comment -->
						</div>
						<!-- End Widget Body -->
					</div>
					<!-- End Widget 04 -->
				</div>






				<div class="col-xl-6  os-animation" data-os-animation="fadeInUp">
					<!-- Begin Widget 04 -->
					<div class="widget widget-04 has-shadow">
						<!-- Begin Widget Header -->
						<div class="widget-header bordered d-flex align-items-center">
							<h2>Support Tickets</h2>
							<div class="widget-options">
								<div class="dropdown">
									<button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle">
										<i class="la la-ellipsis-h"></i>
									</button>
									<!-- <div class="dropdown-menu">
										<a href="#" class="dropdown-item">
											<i class="la la-check"></i>Valid Post
										</a>
										<a href="#" class="dropdown-item">
											<i class="la la-edit"></i>Edit Widget
										</a>
										<a href="faq.html" class="dropdown-item faq">
											<i class="la la-question-circle"></i>FAQ
										</a>
									</div> -->
								</div>
							</div>
						</div>
						<!-- End Widget Header -->
						<!-- Begin Widget Body -->
						<div class="widget-body p-0">
							<div class="post-container">

								<div class="widget-body no-padding">
									<ul class="ticket list-group w-100">
										<!-- 01 -->
										<li class="list-group-item">
											<div class="media">
												<div class="media-left align-self-center pr-4">
													<img src="assets/img/avatar/avatar-02.jpg" class="user-img rounded-circle" alt="...">
												</div>
												<div class="media-body align-self-center">
													<div class="username">
														<h4>Brandon Smith</h4>
													</div>
													<div class="msg">
														<p>Hello, Lorem ipsum dolor sit amet, consectetur
															adipiscing elit, sed do eiusmod tempor incididunt ut
															labore et mauris sapien sem, ornare id mauris vitae,
															ultricies volutpat ...</p>
													</div>
													<div class="status">
														<span class="open mr-2">Open</span>(1 hour ago)
													</div>
												</div>
											</div>
										</li>
										<!-- End 01 -->

										<!-- 03 -->
										<li class="list-group-item">
											<div class="media">
												<div class="media-left align-self-center pr-4">
													<img src="assets/img/avatar/avatar-05.jpg" class="user-img rounded-circle" alt="...">
												</div>
												<div class="media-body align-self-center">
													<div class="username">
														<h4>Megan Duncan</h4>
													</div>
													<div class="msg">
														<p>Hello, Lorem ipsum dolor sit amet, consectetur
															adipiscing elit, sed do eiusmod tempor incididunt ut
															labore et mauris sapien sem, ornare id mauris vitae,
															ultricies volutpat ...</p>
													</div>
													<div class="status">
														<span class="closed mr-2">Closed</span>(1 day ago)
													</div>
												</div>
											</div>
										</li>
										<!-- End 03 -->
									</ul>
								</div>

							</div>
							<!-- Begin Write Comment -->
							<div class="input-group mt-5">
								<input type="text" class="form-control pr-0" placeholder="Write a comment ...">
								<span class="input-group-addon">
									<button class="btn" type="button">
										<i class="la la-smile-o la-2x"></i>
									</button>
								</span>
								<span class="input-group-addon">
									<button class="btn pr-3" type="button">
										<i class="la la-pencil la-2x"></i>
									</button>
								</span>
							</div>
							<!-- End Write Comment -->
						</div>
						<!-- End Widget Body -->
					</div>
					<!-- End Widget 04 -->
				</div>



			</div>
			<!-- End Row -->
		</div>
		<!-- End Container -->
		<!-- Begin Page Footer-->
		<footer class="main-footer">
			<div class="container">
				<div class="row">
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-start justify-content-lg-start justify-content-md-start justify-content-center">
						<p class="text-gradient-02">Design By I-Manager Solutions</p>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-end justify-content-lg-end justify-content-md-end justify-content-center">

					</div>
				</div>
			</div>
		</footer>
		<!-- End Page Footer -->
		<a href="#" class="go-top"><i class="la la-arrow-up"></i></a>
		<!-- Offcanvas Sidebar -->
		<div class="off-sidebar from-right">
			<div class="off-sidebar-container">
				<header class="off-sidebar-header">
					<ul class="button-nav nav nav-tabs mt-3 mb-3 ml-3" role="tablist" id="weather-tab">
						<li><a class="active" data-toggle="tab" href="#messenger" role="tab" id="messenger-tab">Messages</a></li>
						<li><a data-toggle="tab" href="#today" role="tab" id="today-tab">Today</a></li>
					</ul>
					<a href="#off-canvas" class="off-sidebar-close"></a>
				</header>
				<div class="off-sidebar-content offcanvas-scroll auto-scroll">
					<div class="tab-content">
						<!-- Begin Messenger -->

						<!-- End Messenger -->
						<!-- Begin Today -->
						<div role="tabpanel" class="tab-pane fade" id="today" aria-labelledby="today-tab">
							<!-- Begin Today Stats -->
							<div class="sidebar-heading pt-0">Today</div>

							<!-- End Today Stats -->
							<!-- Begin Friends -->
							<div class="sidebar-heading">Friends</div>

							<!-- End Friends -->
							<!-- Begin Settings -->
							<div class="sidebar-heading">Settings</div>

							<!-- End Settings -->
						</div>
						<!-- End Today -->
					</div>
				</div>
				<!-- End Offcanvas Container -->
			</div>
			<!-- End Offsidebar Container -->
		</div>
		<!-- End Offcanvas Sidebar -->
	</div>
	<!-- End Content -->
</div>
<!-- Begin Page Snippets -->
<script src="https://checkout.flutterwave.com/v3.js"></script>
<script src="/admin/assets/vendors/js/nicescroll/nicescroll.min.js"></script>
<script src="/admin/assets/vendors/js/datepicker/moment.min.js"></script>
<script src="/admin/assets/vendors/js/datepicker/daterangepicker.js"></script>
<script src="/admin/assets/vendors/js/app/app.min.js"></script>
<script src="/admin/assets/js/components/validation/validation.min.js"></script>
<script src="/admin/assets/js/components/datepicker/datepicker.js"></script>

<!-- End Page Snippets -->
<script>
	function makeFlutterwavePayment() {

		// if (subs.postPayment) {
		FlutterwaveCheckout({
			public_key: cutomerboard.public_key,
			tx_ref: cutomerboard.tx_ref,
			amount: cutomerboard.amountPayable,
			currency: "NGN",
			country: "NG",
			payment_options: "card,account",
			customer: {
				email: cutomerboard.profileEmail,
				name: cutomerboard.profileName,
			},
			callback: function(response) { // specified callback function
				if (response.status == "successful") {
					cutomerboard.tx_ref = response.tx_ref;
					cutomerboard.amountPayed = response.amount;
					cutomerboard.concludepayment();
				} else {
					// set error
				}
			},
			customizations: {
				title: "BAU CARS LIMITED",
				description: "BAU cars booking payment",

			},
		})
		// }?
	}

	Vue.use(VueToast, {
		// One of options
		position: 'top'
	});

	let cutomerboard = new Vue({
		el: "#cutomerPage",
		data() {
			return {
				//Payment
				public_key: "",
				tx_ref: "",
				amountPayable: 0,
				//Profile
				profileName: "",
				profileDob: "",
				profilePhone: "",
				// profileEmail:""
				profileEmail: "",
				test: "This test",
				bookingHistory: "",
				gettingBookingHistory: true,

				isBookingForm: false, // identifies if the booking form should show
				bookingServiceType: [],
				bookingClass: [],
				billingMethod: [],

				// bookingDetails
				processing: false,
				isSubmittingBookingForm: false,
				bookingDatetime: "",
				selectedServiceType: 50,
				selectedBookingClass: 10,
				selectedBillingMethod: 10,

				bookingPrice: "",

				// Booking
				initializedBooking: [],

				// Support

				supportTickets: [],


			}
		},

		filters: {
			bookingStatus(value) {
				if (value.id == 5) {
					return ""
				}
			}
		},

		computed: {
			hederTitle() {
				if (this.isBookingForm) {
					return "Booking Form"
				} else {
					return "My Profile";
				}
			},



			showBookingForm() {
				this.isBookingForm = true;
			},

			showProfile() {
				this.isBookingForm = false;
			}

		},

		methods: {

			toggleBookingForm() {
				this.isBookingForm = !this.isBookingForm;
			},

			bookingStatus(value) {
				if (value == 5 || value == 10 || value == 20 || value == 30) {
					return "badge-text badge-text-small success";
				} else if (value == 100 || value == 200 || value == 300) {
					return "badge-text badge-text-small  danger";
				} else if (value == 600 || value == 500) {
					return "badge-text badge-text-small info";
				}
			},

			formatPHPDate(date) {
				// myDate = date.replace(/-/g, "/");
				return new Date(date);
			},

			formatPrice(value) {
				let val = (value / 1).toFixed(2).replace(',', '.')
				return val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")
			},
			// Begin Present function 
			getBookingHistory() {
				axios.get("/customer/booking-history").then(res => {
					if (res.status == 200) {
						this.bookingHistory = res.data.data;
						this.gettingBookingHistory = false;
					}
				}).catch(err => {

				});
			},

			getProfile() {
				axios.get("/customer/profile").then(res => {
					if (res.status == 200) {

						this.profileName = res.data.datas[0].fullName;
						this.profileEmail = res.data.datas[0].email;
					}
				}).catch();
			},

			getBookingServiceType() {
				axios.get("/customer/booking-service-type").then(res => {
					if (res.status == 200) {
						this.bookingServiceType = res.data.data;
					}
				}).catch();
			},


			getBookingClass() {
				axios.get("/customer/booking-class").then(res => {
					if (res.status == 200) {
						this.bookingClass = res.data.data
					}
				}).catch();
			},

			getBillingMethod() {
				axios.get("/customer/billing-method").then(res => {
					if (res.status == 200) {
						this.billingMethod = res.data.data;
					}
				}).catch();
			},

			//gets all pending initiated booking
			getInitiatedBooking() {
				axios.get("/customer/initiated-booking").then(res => {
					if (res.status == 200) {
						this.initializedBooking = res.data.data
					}

				}).catch();
			},

			getVal(tes) {
				// console.log(tes);
			},

			// testtoast() {
			// 	console.log("LLLLLL");
			// 	this.$toast.open({
			// 		message: "res.data.messages",
			// 		type: "success",
			// 		duration: 5000,
			// 		dismissible: true
			// 	});
			// 	console.log("NNNNNNN");
			// },

			// End Preset function

			makePayment() {
				this.processing = true;
				let formData = new FormData();
				formData.append("bookingDate", this.$refs.bookingDatetime.value);
				formData.append("selectedService", this.selectedServiceType);
				formData.append("selectedBookingClass", this.selectedBookingClass);
				formData.append("selectedBillingMethod", this.selectedBillingMethod);
				axios.post("/customer/initiatepayment", formData).then(res => {
					if (res.status == 200) {
						this.bookingPrice = res.data.price;
						this.processing = false;
						this.public_key = res.data.public_key;
						this.tx_ref = res.data.txref;
						this.amountPayable = res.data.price;

						makeFlutterwavePayment();
					}
				}).catch();
			},

			concludepayment() {
				let formData = new FormData();
				formData.append("txRef", this.tx_ref);
				formData.append("amountPayed", this.amountPayed);

				axios.post("/customer/concludepayment", formData).then(res => {
					if (res.status == 201) {
						location.reload();
					}
				}).catch();
			},

			calculatePrice() {

				this.processing = true;
				let formData = new FormData();
				formData.append("bookingDate", this.$refs.bookingDatetime.value);
				formData.append("selectedService", this.selectedServiceType);
				formData.append("selectedBookingClass", this.selectedBookingClass);
				formData.append("selectedBillingMethod", this.selectedBillingMethod);
				axios.post("/customer/calculate-price", formData).then(res => {
					if (res.status == 200) {
						this.bookingPrice = res.data.price;
						this.processing = false;
					}
				}).catch();
			},

			createBooking() {
				// this.isSubmittingBookingForm = true;
				this.processing = true;
				if (this.selectedServiceType != "") {

					let formData = new FormData();
					formData.append("bookingDate", this.$refs.bookingDatetime.value);
					formData.append("selectedService", this.selectedServiceType);
					formData.append("selectedBookingClass", this.selectedBookingClass);
					formData.append("selectedBillingMethod", this.selectedBillingMethod);

					axios.post("/customer/create-booking", formData).then(res => {
						if (res.status == 201) {
							// toast alert
							this.$toast.open({
								message: res.data.messages,
								type: "success",
								duration: 20000,
								dismissible: true
							});

							this.isSubmittingBookingForm = false;
							this.getInitiatedBooking();
							this.getBookingHistory();
						}
					}).catch(err => {

					});
				} else {
					this.$toast.open({
						message: res.data.messages,
						type: "error",
						duration: 20000,
						dismissible: true
					})
				}
			},


			// Support

			getSupportSnippet() {
				axios.get("/customer/getsupportsnippet").then(res => {
					if (res.status == 200) {
						this.supportTickets = res.data.data;
					}
				});
			},



			// Booking
			onCancelBooking(id) {
				swal({
					title: "Are you Sure",
					text: "You are about to cancel you booking",
					icon: "warning",
					button: "Continue!",
				}).then(res => {
					this.cancelbooking(id);
				});
			},

			cancelbooking(id) {
				console.log(id);
				let formData = new FormData();
				formData.append("bookingId", id);
				axios.post("/customer/cancelbooking", formData).then(res => {
					if (res.status == 201) {
						window.location.reload();
					}
				}).catch();
			}


		},

		mounted() {
			this.getBookingHistory();
			this.getProfile();
			this.getInitiatedBooking();
			this.getBookingServiceType();
			this.getBookingClass();
			this.getBillingMethod();
		},
	});
</script>