<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Logistics\Module'                        => __DIR__ . '/Module.php',
    'Logistics\Controller\LogisticsController' => __DIR__ . '/src/Logistics/Controller/LogisticsController.php',
    'LogisticsTest\Framework\TestCase'        => __DIR__ . '/tests/Logistics/Framework/TestCase.php',
    'LogisticsTest\SampleTest'                => __DIR__ . '/tests/Logistics/SampleTest.php',
);
