<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JWT\Module'                        => __DIR__ . '/Module.php',
    'JWT\Controller\JWTController' => __DIR__ . '/src/JWT/Controller/JWTController.php',
    'JWTTest\Framework\TestCase'        => __DIR__ . '/tests/JWT/Framework/TestCase.php',
    'JWTTest\SampleTest'                => __DIR__ . '/tests/JWT/SampleTest.php',
);
