<?php
echo $this->headtitle("Drivers");
?>

<?php
$flashMessenger = $this->flashMessenger()
    ->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');
?>
<?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
 <?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
 <?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
 <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>

<div id="drivers">
	<section class="page--header">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6">
					<!-- Page Title Start -->
					<h2 class="page--title h5">DRIVERS</h2>
					<!-- Page Title End -->

					<!-- 				<ul class="breadcrumb"> -->
					<!-- 					<li class="breadcrumb-item"><a href="ecommerce.html">Ecommerce</a></li> -->
					<!-- 					<li class="breadcrumb-item active"><span>Products</span></li> -->
					<!-- 				</ul> -->
				</div>

				<!--                         <div class="col-lg-6"> -->
				<!-- Summary Widget Start -->
				<!--                             <div class="summary--widget"> -->
				<!--                                 <div class="summary--item"> -->
				<!--                                     <p class="summary--chart" data-trigger="sparkline" data-type="bar" data-width="5" data-height="38" data-color="#009378">2,9,7,9,11,9,7,5,7,7,9,11</p> -->

				<!--                                     <p class="summary--title">This Month</p> -->
				<!--                                     <p class="summary--stats text-green">2,371,527</p> -->
				<!--                                 </div> -->

				<!--                                 <div class="summary--item"> -->
				<!--                                     <p class="summary--chart" data-trigger="sparkline" data-type="bar" data-width="5" data-height="38" data-color="#e16123">2,3,7,7,9,11,9,7,9,11,9,7</p> -->

				<!--                                     <p class="summary--title">Last Month</p> -->
				<!--                                     <p class="summary--stats text-orange">2,527,371</p> -->
				<!--                                 </div> -->
				<!--                             </div> -->
				<!-- Summary Widget End -->
				<!--                         </div> -->
			</div>
		</div>
	</section>


	<div id="vCenteredModal" class="modal fade">
		<div class="modal-dialog modal-dialog-centered">

			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">Register A Driver</h5>

					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>

				<div class="modal-body pt-4">
					<div class="form-group">
						<label> <span class="label-text">Driver Full Name</span> <input type="text" v-model='fullname' ref="fullname" class="form-control">
						</label>
					</div>

					<div class="form-group">
						<label> <span class="label-text">Driver Email</span> <input type="email" v-model="email" ref="email" class="form-control">
						</label>
					</div>

					<div class="form-group">
						<label> <span class="label-text">Driver Phone Number</span> <input type="text" @input="acceptNumber" v-model="phoneNumber" ref="phonenumber" class="form-control">
						</label>
					</div>

					<div class="form-group">
						<label> <span class="label-text">Driver Date of Birth</span> <input type="date" v-model="driver_dob" ref="driver_dob" class="form-control">
						</label>
					</div>

					<div class="form-group">
						<label> <span class="label-text">Driving Since</span> <input type="date" v-model="driving_since" ref="driving_since" class="form-control">
						</label>
					</div>



					<hr>

					<h5>Assign a Car</h5>

					<div class="form-group">
						<label> <span class="label-text">Car Plate Number</span> <input type="text" v-model="car_platenumber" ref="car_platenumber" placeholder="Car Plate Number" class="form-control">
						</label>
					</div>

					<div class="form-group">
						<label>
						<span v-if="cars.length" class="label-text">Car Make</span>
						<!-- <div class="col-md-10"> -->
							<select name="select" v-model="selectedCar" class="form-control">
								<option v-for="car in cars"  :key="car.id"  :value="car.id">{{car.carMake}}</option>
								
							</select>
							</label>
						<!-- </div> -->
					</div>


					

					<div class="form-group">
						<label> <span class="label-text">Car Type</span> <input ref="carType" v-model="carType" type="text"  class="form-control">
						</label>
					</div>



<div v-if="creatingDriver">
<div class="spinner"></div></div>


					<button v-else :disabled="submitStatus" @click="createDriver()" type="button" value="Submit" class="btn btn-lg btn-block btn-rounded btn-success">Register Now</button>
						
				</div>
			</div>

		</div>
	</div>


	<section class="main--content">
		<div class="panel">
			<!-- Records Header Start -->
			<div class="records--header">
				<div class="title fa-shopping-bag">
					<h3 class="h3">
						Registered Drivers <a href="#" class="btn btn-sm btn-outline-info">Manage
							Products</a>
					</h3>
					<p>Found Total 1,330 Products</p>
				</div>

				<div class="actions">
					<form action="#" class="search flex-wrap flex-md-nowrap">
						<input type="text" class="form-control" placeholder="Product Name..." required> <select name="select" class="form-control">
							<option value="" selected>Product Category</option>
						</select>
						<button type="submit" class="btn btn-rounded">
							<i class="fa fa-search"></i>
						</button>
					</form>

					<a href="#vCenteredModal" data-toggle="modal" class=" btn btn-lg  btn-rounded btn-warning">ADD DRIVER</a>
				</div>
			</div>
			<!-- Records Header End -->
		</div>

		<div class="panel">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    Registered Drivers
                                </h3>

                                <div class="dropdown">
                                    

                                    
                                </div>
                            </div>

                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table style--2">
                                        <thead>
                                            <tr>
                                               
                                                <th>Driver UID</th>
                                                <th>Driver Name</th>
                                                <th>Driveing Since</th>
<!--                                                 <th>Quantity</th> -->
<!--                                                 <th>Tracking No.</th> -->
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <!-- Table Row Start -->
                                            <?php 
                                            if(count($drivers) > 0):
                                            foreach ($drivers as $driver):?>
                                            <tr>
                                               
                                                <td><?php echo strtoupper($driver["diverUid"])?></td>
                                                <td><a href="#" class="btn-link"><?php  echo $driver["user"]["fullName"]?></a></td>
                                                <td><?php echo $this->dateformat($driver["driverSince"], IntlDateFormatter::MEDIUM)?></td>
<!--                                                 <td>2</td> -->
<!--                                                 <td><span class="text-muted">#BG6R9853lP</span></td> -->
                                                <td><i class="fa fa-edit"></i> Edit</td>
                                            </tr>
                                            <?php endforeach;
                                            endif;
                                            ?>
                                            <!-- Table Row End -->

                                           
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
	</section>
</div>

<script>
	let driver = new Vue({
		el: "#drivers",
		data() {
			return {
				phoneNumber: "",
				creatingDriver:false,
				email: "",
				reg: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,24}))$/,
				fullname: "",
				driver_dob:'',
				driving_since:'',
				car_platenumber:'',
				cars:[],
				selectedCar:"",
				carType:'',
				
			}
		},
		mounted() {
			this.getCarMake()
		},

		computed: {
			submitStatus() {
				if (this.phoneNumber == ""  || this.fullname == "" || this.driver_dob == "" || this.driving_since == "" ) {
					return true;
				} else {
					return false;
				}


			},

			isEmailValid() {
				return this.reg.test(this.email);
			}
		},

		methods: {
			getCarMake(){
				axios.get("/controller/driver/allcarsmake").then(res=>{
					this.cars = res.data.data;
				})
			},
			createDriver() {
				this.creatingDriver = true;
				let formData = new FormData();
				formData.append("fullname", this.fullname);
				formData.append("email", this.email);
				formData.append("phoneNumber", this.phoneNumber);
				formData.append("driver_dob", this.driver_dob);
				formData.append("driving_since", this.driving_since);
				formData.append("selectedCar", this.selectedCar);
				formData.append("car_platenumber", this.car_platenumber);
				formData.append("carType", this.carType);
				axios.post("/controller/driver/createdriver", formData).then(res=>{
					if(res.status == 201){
						this.creatingDriver = false;
						window.location.reload();
					}
				}).catch(err=>{
					
						console.log(err.response.data.message);
					
				});
			},

			acceptNumber() {
				var x = this.phoneNumber.replace(/\D/g, '').match(/(\d{0,4})(\d{0,3})(\d{0,4})/);
				this.phoneNumber = !x[2] ? x[1] : '' + x[1] + '-' + x[2] + (x[3] ? '-' + x[3] : '');
			}
		},
	});
</script>