<!-- Begin Sign In -->
<div role="tabpanel" class="tab-pane show active" id="singin"
	aria-labelledby="singin-tab">
	<h3>Sign In </h3>
	<form>
		<div class="group material-input">
			<input type="text" ref="phoneOrEmail" required> <span class="highlight"></span> <span
				class="bar"></span> <label>Email</label>
		</div>
		<div class="group material-input">
			<input type="password" ref="password" required> <span class="highlight"></span> <span
				class="bar"></span> <label>Password</label>
		</div>
	</form>
	<div class="row">
		<div class="col text-left">
			<div class="styled-checkbox">
				<input type="checkbox" name="checkbox" id="remeber"> <label
					for="remeber">Remember me</label>
			</div>
		</div>
		<div class="col text-right">
			<a href=" ">Forgot Password ?</a>
		</div>
	</div>
	<div class="sign-btn text-center">
		<button @click="login()" href="db-default.html" class="btn btn-lg btn-gradient-01"> Sign In
		</button>
	</div>
</div>
<!-- End Sign In -->

<script>

let login = new Vue({
	el:"#singin",
	data() {
		return {
			
		}
	},
	methods: {
		login(){
			
		}
	},
});
</script>