<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Wallet\Module'                        => __DIR__ . '/Module.php',
    'Wallet\Controller\WalletController' => __DIR__ . '/src/Wallet/Controller/WalletController.php',
    'WalletTest\Framework\TestCase'        => __DIR__ . '/tests/Wallet/Framework/TestCase.php',
    'WalletTest\SampleTest'                => __DIR__ . '/tests/Wallet/SampleTest.php',
);
