<?php
echo $this->headtitle("About Us");

?>

<section id="page-title-area" class="section-padding overlay">
	<div class="container">
		<div class="row">
			<!-- Page Title Start -->
			<div class="col-lg-12">
				<div class="section-title  text-center">
					<h2>About US</h2>
					<span class="title-line"><i class="fa fa-car"></i></span>
					<!-- 					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p> -->
				</div>
			</div>
			<!-- Page Title End -->
		</div>
	</div>
</section>


<section id="about-area" class="section-padding">
	<div class="container">
		<div class="row">
			<!-- Section Title Start -->
			<div class="col-lg-12">
				<div class="section-title  text-center">
					<h2>About us</h2>
					<span class="title-line"><i class="fa fa-car"></i></span>
					<p>Your Security Is Our Top Priority</p>
				</div>
			</div>
			<!-- Section Title End -->
		</div>

		<div class="row">
			<!-- About Content Start -->
			<div class="col-lg-6">
				<div class="display-table">
					<div class="display-table-cell">
						<div class="about-content">
							<p>When you are renting a car in Lagos, Bau Cars provide the
								flexibility of having a vehicle anytime you want, as well as the
								assurance of a sanitized and virus free car with experience and
								security assured</p>
							<p>With a wide range of vehicles to select from, Bau Cars offer
								convenient Car ; with a driver, to drive down to nearby cities
								or to manoeuvre through traffic as you head from one important
								business meeting to the next.</p>
						</div>
					</div>
				</div>
			</div>
			<!-- About Content End -->

			<!-- About Video Start -->
			<div class="col-lg-6">
				<div class="about-image">
					<img src="assets/img/home-2-about.png" alt="JSOFT">
				</div>
			</div>
			<!-- About Video End -->
		</div>

		<!-- About Fretutes Start -->
		<div class="about-feature-area">
			<div class="row">
				<!-- Single Fretutes Start -->
				<div class="col-lg-4">
					<div class="about-feature-item active">
						<i class="fa fa-car"></i>
						<h3>SECURITY</h3>
						<p>From our drivers to our logistics control room, we provide
							securit at all levels of our operation</p>
					</div>
				</div>
				<!-- Single Fretutes End -->

				<!-- Single Fretutes Start -->
				<div class="col-lg-4">
					<div class="about-feature-item">
						<i class="fa fa-car"></i>
						<h3>SAFETY</h3>
						<p>With experinced drivers, well inspected vehichles and valid
							insurances, the safety of our customer is premium .</p>
					</div>
				</div>
				<!-- Single Fretutes End -->

				<!-- Single Fretutes Start -->
				<div class="col-lg-4">
					<div class="about-feature-item">
						<i class="fa fa-car"></i>
						<h3>COMFORT</h3>
						<p>No matter the weather, road, or environmental condition, we
							provide comfort that stands out</p>
					</div>
				</div>
				<!-- Single Fretutes End -->
			</div>
		</div>
		<!-- About Fretutes End -->
	</div>
</section>
<!--== About Page Content End ==-->