<?php
echo $this->headtitle("Our Service");

?>
<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
	<div class="container">
		<div class="row">
			<!-- Page Title Start -->
			<div class="col-lg-12">
				<div class="section-title  text-center">
					<h2>Our Services</h2>
					<span class="title-line"><i class="fa fa-car"></i></span>
<p>Your Security Is Our Top Priority</p> 
				</div>
			</div>
			<!-- Page Title End -->
		</div>
	</div>
</section>
<!--== Page Title Area End ==-->


<!--== Service Page Content Start ==-->
<section id="service-page-wrapper" class="section-padding">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<!-- Single Services Start -->
				<div class="single-service-item">
					<div class="service-item-thumb ser-thumb-bg-1"></div>
					<div class="service-item-content">
						<h3>CAR RENTAL</h3>
						<p>BAU CARS offers an array of vehicles at very affordable
							rates</p>
						<p>We provide the best alternative to commuting and logistics
							through a strong network of high technological solutions that
							makes transportation accessible and affordable.</p>
						<p>
							For your transport and logistics services, BAU Cars brings you
							the following Rental Services in Lagos: <br>Car Rental, Luxury
							Car Rental, Airport Pick-up and Drop-off, SUV Rental, Corporate
							Car or Bus Charter, Private Car Charter Service, School Bus
							Service, Staff Bus Service, Event Bus Charter
						</p>
					</div>
				</div>
				<!-- Single Services End -->

				<!-- Single Services Start -->
				<div class="single-service-item">
					<div class="service-item-thumb ser-thumb-bg-2 d-lg-none d-md-block"></div>
					<div class="service-item-content">
						<h3>AIRPORT PICKUP</h3>
						<p>Providing timely service for, all airport service in a security and health concious enviroment </p>
					</div>
					<div
						class="service-item-thumb ser-thumb-bg-2 d-none d-lg-block d-md-none"></div>
				</div>
				<!-- Single Services End -->

				<!-- Single Services Start -->
				<div class="single-service-item">
					<div class="service-item-thumb ser-thumb-bg-3"></div>
					<div class="service-item-content">
						<h3>LUXURY SERVICE</h3>
						<p></p>
					</div>
				</div>
				<!-- Single Services End -->

				<!-- Single Services Start -->
				<div class="single-service-item">
					<div class="service-item-thumb ser-thumb-bg-4 d-lg-none d-md-block"></div>
					<div class="service-item-content">
						<h3>PARCEL LOGISTICS</h3>
						<p></p>
					</div>
					<div
						class="service-item-thumb ser-thumb-bg-2 d-none d-lg-block d-md-none"></div>
				</div>
				<!-- Single Services End -->
			</div>
		</div>
	</div>
</section>
<!--== Service Page Content End ==-->




<!--== Partner Area Start ==-->

<!--== Partner Area End ==-->